services:
  comfyui-worker:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=${{ env.SERVE_API_LOCALLY }}
      - GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}
      - HUGGINGFACE_ACCESS_TOKEN=${{ env.HUGGINGFACE_ACCESS_TOKEN }}
      - VERSION=${{ env.VERSION }}
    ports:
      - "8188:8188"
    volumes:
      - /Users/alexgenovese/Desktop/runpod/output:/comfyui/output
      - /Users/alexgenovese/Desktop/runpod/volume:/runpod-volume
