version: "3.8"

services:
  comfyui:
    image: timpietruskyblibla/runpod-worker-comfy:dev
    container_name: comfyui-worker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    runtime: nvidia
    volumes:
      - ./data/comfyui/output:/comfyui/output # TODO l'immagine ce la manderà in base64 
      - ./data/models:/comfyui/models
      - ./data/nodes:/comfyui/custom_nodes 
      - ./data/workflows:/comfyui/workflows
