services:
  comfyui-worker:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=false
      - GITHUB_TOKEN=${ secrets.BLIBLA_SEMANTIC_RELEASE }
      - HUGGINGFACE_ACCESS_TOKEN=${ secrets.HUGGINGFACE_ACCESS_TOKEN }
      - VERSION=${ vars.VERSION }
    ports:
      - "8188:8188"
    volumes:
      - /Users/alexgenovese/Desktop/runpod/output:/comfyui/output
      - /Users/alexgenovese/Desktop/runpod/volume:/runpod-volume
